# Generated by Django 6.0.2 on 2026-02-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('completion_status', models.BooleanField(default=False)),
                ('creation_date', models.DateField()),
                ('due_date', models.DateField()),
            ],
        ),
    ]
